@api = http://localhost:8001/api/v1


# ===== get new accessJWT
GET {{api}}/users/new-accessjwt
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFAYS5jb20iLCJpYXQiOjE3MTkyNzA5MTYsImV4cCI6MTcyMTg2MjkxNn0.9RPsVE0Gg0b6EZiZHKi1yTu4fNzz6xKlZ9lHxCi4hmk

### ===== Forget password
POST {{api}}/users/otp
Content-Type: application/json

{
    "email": "a@a.com"
}


# ============= categoris
### post new cat
POST {{api}}/categories
Content-Type: application/json

{
    "title": "New Laptops"
}